# Generated by Django 3.1.2 on 2023-03-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='tool_ID',
            new_name='sensor_id',
        ),
    ]
