# Generated by Django 3.1.2 on 2023-03-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20230313_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
